services:
  media:
    image: dugon/media:latest
    volumes:
      - ./media/config.js:/code/config.js
    depends_on:
      - nats_server
    network_mode: host
  signal:
    image: dugon/signal:latest
    volumes:
      - ./signal/config.toml:/root/config.toml
    ports:
      - 8800:8800
    depends_on:
      - nats_server
  nats_server:
    image: nats:scratch
    ports:
      - 4222:4222